name = "SimpleSymbolicIntegration"
uuid = "dd4b6e7d-19cb-41bd-bc73-fc520c048017"
authors = ["Karl Royen <wessel.karl@googlemail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[compat]
SymbolicUtils = "3.17.1"
TermInterface = "2.0.0"
julia = "1.6.7"

[extras]
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SymbolicUtils"]
